//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hızlı_Satış.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class KeyboardColor : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyboardColor defaultInstance = ((KeyboardColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyboardColor())));
        
        public static KeyboardColor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1abc9c")]
        public string rakamrenk {
            get {
                return ((string)(this["rakamrenk"]));
            }
            set {
                this["rakamrenk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#34495e")]
        public string harfrenk {
            get {
                return ((string)(this["harfrenk"]));
            }
            set {
                this["harfrenk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#e67e22")]
        public string digerrenk {
            get {
                return ((string)(this["digerrenk"]));
            }
            set {
                this["digerrenk"] = value;
            }
        }
    }
}
