//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hızlı_Satış.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class KullanimAyarlari : global::System.Configuration.ApplicationSettingsBase {
        
        private static KullanimAyarlari defaultInstance = ((KullanimAyarlari)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KullanimAyarlari())));
        
        public static KullanimAyarlari Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string varsayilansifre {
            get {
                return ((string)(this["varsayilansifre"]));
            }
            set {
                this["varsayilansifre"] = value;
            }
        }
    }
}
